"""Read and write Google Sheets cell values via the Sheets API v4.

Distinct from ``gdrives export``, which downloads a *whole* spreadsheet to a
local ``.xlsx``/``.csv`` file through the Drive API. Here we operate on live
cell ranges with ``spreadsheets.values.*`` (get/update/append/clear), so callers
can read a range into rows and write rows back without a round-trip through a
file.

The package re-exports its public surface here, so ``from gdrives.sheets import
pull_values`` works regardless of which submodule defines a name:

- ``values``: ``spreadsheets.values.*`` wrappers, render options, tab
  lookups, and the structural ``spreadsheets.batchUpdate``
- ``retry``: ``with_retry`` and the retryable status sets
- ``cells``: canonical cell strings, column types, typed rows, row keys, and
  schema checks
- ``a1``: A1 notation and ``GridRange`` conversion
- ``match``: keyed row updates (``find_rows``, ``set_by_match``)
- ``rules``: conditional format rules
- ``files``: local CSV/TSV grids, and CSV/TSV/JSON record files
- ``config``: the sync config file (``gdrives-sheets.json``), loaded and checked
- ``table``: ``read_tab`` and ``parse_tab``, a whole tab as header-named, keyed
  records, with declared date columns read from their serial numbers
- ``merge``: ``merge``, the pure three-way merge of local records and a tab
- ``apply``: ``apply_plan``, which writes a merge plan's sheet side, guarded
  and read back, and ``insert_point``, the row its new rows go above
- ``stores``: where a tab's local side and its base are kept (``Store``,
  ``FileStore``, ``MemoryStore``)
- ``structure``: add, place, and delete columns by header name, create
  missing tabs, and set column widths
- ``sync``: keep a tab and a local file in step (``plan_tab``, ``apply_tab``,
  ``pull_tab``, ``push_tab``, ``push_rows``, ``pull_all_tabs``,
  ``run_target``) and report it
- ``commands``: the ``run_*`` CLI entry points
"""

from gdrives.sheets.a1 import (
    a1_quote,
    a1_to_grid_range,
    column_index,
    column_letter,
    grid_range_to_a1,
    split_a1,
)
from gdrives.sheets.apply import (
    ApplyError,
    ApplyResult,
    ReadBackError,
    SheetChangedError,
    apply_plan,
    insert_point,
    verify,
)
from gdrives.sheets.cells import (
    BLANK_KEYS,
    COLUMN_TYPES,
    SERIAL_TYPES,
    ColumnSchema,
    Problem,
    cell_problem,
    check_blank_keys,
    column_type,
    decode_rows,
    encode_rows,
    from_cell,
    index_rows,
    normalize_cell,
    normalize_key,
    problems,
    row_key,
    serial_to_cell,
    to_cell,
)
from gdrives.sheets.commands import (
    format_values,
    run_add_rule,
    run_append,
    run_clear,
    run_delete_rule,
    run_get,
    run_pull,
    run_push,
    run_rules,
    run_set,
    run_sync,
    run_update,
)
from gdrives.sheets.config import (
    BOOTSTRAPS,
    CONFIG_NAME,
    INPUT_OPTIONS,
    LOCAL_EXTENSIONS,
    MODES,
    ON_INVALID,
    Config,
    ConfigError,
    TabConfig,
    Target,
    find_config,
    load_config,
    parse_config,
)
from gdrives.sheets.files import (
    NEWLINES,
    Records,
    read_records,
    read_values_csv,
    write_records,
    write_values_csv,
)
from gdrives.sheets.match import find_rows, parse_pairs, set_by_match
from gdrives.sheets.merge import (
    OVERRIDE_REASONS,
    ROW_FLAGS,
    SIDES,
    Cell,
    HeldCell,
    MergePlan,
    NewRow,
    Override,
    RowFlag,
    merge,
)
from gdrives.sheets.retry import IDEMPOTENT_STATUSES, RATE_LIMIT_STATUSES, with_retry
from gdrives.sheets.rules import (
    add_conditional_rule,
    build_formula_rule,
    color_to_hex,
    delete_conditional_rule,
    describe_rule,
    format_rules,
    hex_to_color,
    list_conditional_rules,
    read_rule_json,
)
from gdrives.sheets.stores import FileStore, MemoryStore, Store
from gdrives.sheets.structure import (
    add_columns,
    delete_columns,
    ensure_tabs,
    place_columns,
    set_column_widths,
)
from gdrives.sheets.sync import (
    STAGES,
    CheckContext,
    Replacement,
    SyncReport,
    TabPlan,
    TabReport,
    apply_tab,
    format_report,
    plan_tab,
    pull_all_tabs,
    pull_tab,
    push_rows,
    push_tab,
    run_target,
    sync_tab,
)
from gdrives.sheets.table import (
    EmptyTabError,
    Table,
    parse_tab,
    pull_serials,
    read_tab,
)
from gdrives.sheets.values import (
    FORMATTED_STRING,
    FORMATTED_VALUE,
    FORMULA,
    RAW,
    SERIAL_NUMBER,
    UNFORMATTED_VALUE,
    USER_ENTERED,
    GridTooLargeError,
    TabGrid,
    append_values,
    batch_update_spreadsheet,
    batch_update_values,
    clear_values,
    decode_errors,
    first_tab,
    list_tabs,
    pull_grid,
    pull_many,
    pull_values,
    tab_grid,
    tab_sheet_ids,
    update_values,
)

__all__ = [
    "BLANK_KEYS",
    "ApplyError",
    "ApplyResult",
    "BOOTSTRAPS",
    "COLUMN_TYPES",
    "CONFIG_NAME",
    "Cell",
    "CheckContext",
    "ColumnSchema",
    "Config",
    "ConfigError",
    "EmptyTabError",
    "FORMATTED_STRING",
    "FileStore",
    "FORMATTED_VALUE",
    "FORMULA",
    "GridTooLargeError",
    "IDEMPOTENT_STATUSES",
    "HeldCell",
    "INPUT_OPTIONS",
    "LOCAL_EXTENSIONS",
    "MODES",
    "MemoryStore",
    "MergePlan",
    "NEWLINES",
    "NewRow",
    "ON_INVALID",
    "OVERRIDE_REASONS",
    "Override",
    "Problem",
    "RATE_LIMIT_STATUSES",
    "RAW",
    "ROW_FLAGS",
    "ReadBackError",
    "Records",
    "Replacement",
    "RowFlag",
    "SERIAL_NUMBER",
    "SERIAL_TYPES",
    "SIDES",
    "STAGES",
    "SheetChangedError",
    "Store",
    "SyncReport",
    "TabConfig",
    "TabGrid",
    "TabPlan",
    "TabReport",
    "Table",
    "Target",
    "UNFORMATTED_VALUE",
    "USER_ENTERED",
    "a1_quote",
    "a1_to_grid_range",
    "add_columns",
    "add_conditional_rule",
    "append_values",
    "apply_plan",
    "apply_tab",
    "batch_update_spreadsheet",
    "batch_update_values",
    "build_formula_rule",
    "cell_problem",
    "check_blank_keys",
    "clear_values",
    "color_to_hex",
    "column_index",
    "column_letter",
    "column_type",
    "decode_rows",
    "decode_errors",
    "delete_columns",
    "delete_conditional_rule",
    "describe_rule",
    "encode_rows",
    "ensure_tabs",
    "find_config",
    "find_rows",
    "first_tab",
    "format_report",
    "format_rules",
    "format_values",
    "from_cell",
    "grid_range_to_a1",
    "hex_to_color",
    "index_rows",
    "insert_point",
    "list_conditional_rules",
    "list_tabs",
    "load_config",
    "merge",
    "normalize_cell",
    "normalize_key",
    "parse_config",
    "parse_pairs",
    "parse_tab",
    "place_columns",
    "plan_tab",
    "problems",
    "pull_all_tabs",
    "pull_grid",
    "pull_many",
    "pull_serials",
    "pull_tab",
    "pull_values",
    "push_rows",
    "push_tab",
    "read_records",
    "read_rule_json",
    "read_tab",
    "read_values_csv",
    "row_key",
    "run_add_rule",
    "run_append",
    "run_clear",
    "run_delete_rule",
    "run_get",
    "run_pull",
    "run_push",
    "run_rules",
    "run_set",
    "run_sync",
    "run_target",
    "run_update",
    "serial_to_cell",
    "set_by_match",
    "set_column_widths",
    "split_a1",
    "sync_tab",
    "tab_grid",
    "tab_sheet_ids",
    "to_cell",
    "update_values",
    "verify",
    "with_retry",
    "write_records",
    "write_values_csv",
]
