"""Read and write Google Sheets cell values via the Sheets API v4.

Distinct from ``gdrives export``, which downloads a *whole* spreadsheet to a
local ``.xlsx``/``.csv`` file through the Drive API. Here we operate on live
cell ranges with ``spreadsheets.values.*`` (get/update/append/clear), so callers
can read a range into rows and write rows back without a round-trip through a
file.

The package re-exports its public surface here, so ``from gdrives.sheets import
pull_values`` works regardless of which submodule defines a name:

- ``values``: ``spreadsheets.values.*`` wrappers, render options, tab
  lookups, and the structural ``spreadsheets.batchUpdate``
- ``retry``: ``with_retry``, the retryable status sets, ``retry_notices``, and
  ``print_retry``
- ``cells``: canonical cell strings, column types, typed rows, row keys, and
  schema checks
- ``a1``: A1 notation and ``GridRange`` conversion
- ``match``: keyed row updates (``find_rows``, ``set_by_match``)
- ``rules``: conditional format rules
- ``files``: local CSV/TSV grids, and CSV/TSV/JSON record files
- ``create``: ``create_spreadsheet``, a native spreadsheet in a Drive folder
  (empty, or converted from a local workbook), and ``name_tabs``
- ``config``: the sync config file (``gdrives-sheets.json``), loaded and checked
- ``hooks``: the hooks and schema references a config names, found when a
  run starts (``resolve_target``, ``resolve_tab``, ``resolve_hooks``,
  ``tab_hooks``)
- ``table``: ``read_tab`` and ``parse_tab``, a whole tab as header-named, keyed
  records, with declared date columns read from their serial numbers
- ``merge``: ``merge``, the pure three-way merge of local records and a tab
- ``apply``: ``apply_plan``, which writes a merge plan's sheet side, guarded
  and read back, and ``insert_point``, the row its new rows go above
- ``typed``: typed writes, declared columns written as values
  (``typed_columns``, ``dated_cells``, ``format_requests``)
- ``retype``: ``retype_columns``, which turns the text a typed column holds
  into values
- ``order``: ``reorder_rows``, which puts a keyed tab's rows in a given
  order by moving whole rows
- ``stores``: where a tab's local side and its base are kept (``Store``,
  ``FileStore``, ``JsonEntryStore``, ``MemoryStore``)
- ``structure``: add, place, and delete columns by header name, create
  missing tabs, set column widths, and find and clear link formatting
- ``schema``: a target's schemas as rows of documentation (``schema_rows``,
  ``format_schema``)
- ``links``: ``sweep_url_links`` and ``format_sweep``, the links of URL cells
  over a spreadsheet's tabs
- ``sync``: keep a tab and a local file in step (``plan_tab``, ``apply_tab``,
  ``pull_tab``, ``pull_records``, ``push_tab``, ``push_rows``, ``pull_all_tabs``,
  ``run_target``) and report it
- ``transforms``: stock ``transform`` hooks (``trim_cells``)
- ``commands``: the ``run_*`` CLI entry points
"""

from gdrives.local import NEWLINES
from gdrives.sheets.a1 import (
    a1_quote,
    a1_to_grid_range,
    column_index,
    column_letter,
    grid_range_to_a1,
    split_a1,
)
from gdrives.sheets.apply import (
    ApplyError,
    ApplyResult,
    ReadBackError,
    SheetChangedError,
    apply_plan,
    insert_point,
    verify,
)
from gdrives.sheets.cells import (
    BLANK_KEYS,
    COLUMN_TYPES,
    DATE_FORMATS,
    PATTERN_TYPES,
    SERIAL_TYPES,
    STRICT_TYPES,
    ColumnSchema,
    Problem,
    cell_data,
    cell_problem,
    check_blank_keys,
    column_type,
    decode_rows,
    encode_rows,
    from_cell,
    index_rows,
    normalize_cell,
    normalize_key,
    problems,
    row_key,
    serial_to_cell,
    to_cell,
    to_serial,
)
from gdrives.sheets.commands import (
    format_values,
    run_add_rule,
    run_append,
    run_clear,
    run_create,
    run_delete_rule,
    run_get,
    run_links,
    run_pull,
    run_push,
    run_rules,
    run_schema,
    run_set,
    run_sync,
    run_update,
    run_widths,
)
from gdrives.sheets.config import (
    BOOTSTRAPS,
    CONFIG_NAME,
    HOOKS,
    INPUT_OPTIONS,
    LOCAL_EXTENSIONS,
    MODES,
    ON_INVALID,
    TARGET_DEFAULTS,
    Config,
    ConfigError,
    TabConfig,
    Target,
    find_config,
    load_config,
    parse_config,
)
from gdrives.sheets.create import (
    SOURCE_MIMES,
    SPREADSHEET_MIME,
    check_source,
    check_tabs,
    create_spreadsheet,
    name_tabs,
    spreadsheet_url,
)
from gdrives.sheets.files import (
    Records,
    read_records,
    read_values_csv,
    write_records,
    write_values_csv,
)
from gdrives.sheets.hooks import (
    resolve_hooks,
    resolve_schemas,
    resolve_tab,
    resolve_target,
    tab_hooks,
)
from gdrives.sheets.links import LinkSweep, TabLinks, format_sweep, sweep_url_links
from gdrives.sheets.match import find_rows, parse_pairs, set_by_match
from gdrives.sheets.merge import (
    OVERRIDE_REASONS,
    ROW_FLAGS,
    SIDES,
    Cell,
    HeldCell,
    MergePlan,
    NewRow,
    Override,
    RowFlag,
    merge,
)
from gdrives.sheets.order import ReorderResult, reorder_rows
from gdrives.sheets.retry import (
    IDEMPOTENT_STATUSES,
    RATE_LIMIT_STATUSES,
    RetryNotice,
    print_retry,
    retry_notices,
    with_retry,
)
from gdrives.sheets.retype import RetypeCell, RetypeReport, retype_columns
from gdrives.sheets.rules import (
    add_conditional_rule,
    build_formula_rule,
    color_to_hex,
    delete_conditional_rule,
    describe_rule,
    format_rules,
    hex_to_color,
    list_conditional_rules,
    read_rule_json,
)
from gdrives.sheets.schema import format_schema, schema_rows
from gdrives.sheets.stores import FileStore, JsonEntryStore, MemoryStore, Store
from gdrives.sheets.structure import (
    CELL_LINK_FIELD,
    CELL_STYLE_FIELDS,
    LINK_COLOR,
    LINK_DETAIL_FIELDS,
    LINK_FIELDS,
    LINK_STYLE_REASONS,
    RUNS_FIELD,
    URL_LINK_REASONS,
    WIDTH_FIELDS,
    LinkedCell,
    StyledCell,
    UrlLinkProblem,
    add_columns,
    clear_link_format,
    delete_columns,
    ensure_tabs,
    get_column_widths,
    link_clear,
    linked_cells,
    place_columns,
    set_column_widths,
    set_url_links,
    strip_links,
    styled_cells,
    url_link_problems,
)
from gdrives.sheets.sync import (
    STAGES,
    CheckContext,
    PullError,
    Replacement,
    SyncReport,
    TabPlan,
    TabReport,
    apply_tab,
    format_report,
    plan_tab,
    pull_all_tabs,
    pull_records,
    pull_tab,
    push_rows,
    push_tab,
    run_target,
    sync_tab,
)
from gdrives.sheets.table import (
    EmptyTabError,
    Table,
    parse_tab,
    pull_serials,
    read_tab,
)
from gdrives.sheets.transforms import trim_cells
from gdrives.sheets.typed import (
    NUMBER_FORMAT_FIELD,
    dated_cells,
    format_requests,
    typed_columns,
)
from gdrives.sheets.values import (
    FORMATTED_STRING,
    FORMATTED_VALUE,
    FORMULA,
    RAW,
    RENDERS,
    SERIAL_NUMBER,
    UNFORMATTED_VALUE,
    USER_ENTERED,
    GridTooLargeError,
    TabGrid,
    TabListing,
    append_values,
    batch_update_spreadsheet,
    batch_update_values,
    clear_values,
    decode_errors,
    first_tab,
    list_tabs,
    pull_grid,
    pull_many,
    pull_values,
    tab_grid,
    tab_listing,
    tab_sheet_ids,
    update_values,
)

__all__ = [
    "DATE_FORMATS",
    "NUMBER_FORMAT_FIELD",
    "RetypeCell",
    "RetypeReport",
    "cell_data",
    "dated_cells",
    "format_requests",
    "retype_columns",
    "to_serial",
    "typed_columns",
    "BLANK_KEYS",
    "ApplyError",
    "ApplyResult",
    "BOOTSTRAPS",
    "CELL_LINK_FIELD",
    "CELL_STYLE_FIELDS",
    "COLUMN_TYPES",
    "CONFIG_NAME",
    "Cell",
    "CheckContext",
    "ColumnSchema",
    "Config",
    "ConfigError",
    "EmptyTabError",
    "FORMATTED_STRING",
    "FileStore",
    "FORMATTED_VALUE",
    "FORMULA",
    "GridTooLargeError",
    "IDEMPOTENT_STATUSES",
    "JsonEntryStore",
    "HeldCell",
    "HOOKS",
    "INPUT_OPTIONS",
    "LINK_COLOR",
    "LINK_DETAIL_FIELDS",
    "LINK_FIELDS",
    "LINK_STYLE_REASONS",
    "LOCAL_EXTENSIONS",
    "LinkSweep",
    "LinkedCell",
    "MODES",
    "MemoryStore",
    "MergePlan",
    "NEWLINES",
    "NewRow",
    "ON_INVALID",
    "OVERRIDE_REASONS",
    "Override",
    "PATTERN_TYPES",
    "Problem",
    "PullError",
    "RATE_LIMIT_STATUSES",
    "RAW",
    "RENDERS",
    "ROW_FLAGS",
    "RUNS_FIELD",
    "RetryNotice",
    "ReadBackError",
    "ReorderResult",
    "Records",
    "Replacement",
    "RowFlag",
    "SERIAL_NUMBER",
    "SERIAL_TYPES",
    "SIDES",
    "SOURCE_MIMES",
    "SPREADSHEET_MIME",
    "STAGES",
    "STRICT_TYPES",
    "SheetChangedError",
    "Store",
    "StyledCell",
    "SyncReport",
    "TARGET_DEFAULTS",
    "TabConfig",
    "TabGrid",
    "TabLinks",
    "TabListing",
    "TabPlan",
    "TabReport",
    "Table",
    "Target",
    "UNFORMATTED_VALUE",
    "URL_LINK_REASONS",
    "USER_ENTERED",
    "UrlLinkProblem",
    "WIDTH_FIELDS",
    "a1_quote",
    "a1_to_grid_range",
    "add_columns",
    "add_conditional_rule",
    "append_values",
    "apply_plan",
    "apply_tab",
    "batch_update_spreadsheet",
    "batch_update_values",
    "build_formula_rule",
    "cell_problem",
    "check_blank_keys",
    "check_source",
    "check_tabs",
    "clear_link_format",
    "clear_values",
    "color_to_hex",
    "column_index",
    "column_letter",
    "column_type",
    "create_spreadsheet",
    "decode_rows",
    "decode_errors",
    "delete_columns",
    "delete_conditional_rule",
    "describe_rule",
    "encode_rows",
    "ensure_tabs",
    "find_config",
    "find_rows",
    "first_tab",
    "format_report",
    "format_schema",
    "format_rules",
    "format_sweep",
    "format_values",
    "from_cell",
    "get_column_widths",
    "grid_range_to_a1",
    "hex_to_color",
    "index_rows",
    "insert_point",
    "link_clear",
    "linked_cells",
    "list_conditional_rules",
    "list_tabs",
    "load_config",
    "merge",
    "name_tabs",
    "normalize_cell",
    "normalize_key",
    "parse_config",
    "parse_pairs",
    "parse_tab",
    "place_columns",
    "plan_tab",
    "print_retry",
    "problems",
    "pull_all_tabs",
    "pull_grid",
    "pull_many",
    "pull_records",
    "pull_serials",
    "pull_tab",
    "pull_values",
    "push_rows",
    "push_tab",
    "read_records",
    "read_rule_json",
    "read_tab",
    "read_values_csv",
    "reorder_rows",
    "resolve_hooks",
    "resolve_schemas",
    "resolve_tab",
    "resolve_target",
    "row_key",
    "run_add_rule",
    "run_append",
    "run_clear",
    "run_create",
    "run_delete_rule",
    "run_get",
    "run_links",
    "run_pull",
    "run_push",
    "run_rules",
    "run_schema",
    "run_set",
    "run_sync",
    "run_target",
    "retry_notices",
    "run_update",
    "run_widths",
    "serial_to_cell",
    "set_by_match",
    "set_column_widths",
    "set_url_links",
    "split_a1",
    "spreadsheet_url",
    "strip_links",
    "styled_cells",
    "sweep_url_links",
    "schema_rows",
    "sync_tab",
    "tab_grid",
    "tab_hooks",
    "tab_listing",
    "tab_sheet_ids",
    "to_cell",
    "trim_cells",
    "update_values",
    "url_link_problems",
    "verify",
    "with_retry",
    "write_records",
    "write_values_csv",
]
